// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQBpnuMeV72HPEX6GwKlQouURBlUsDgwo',
    appId: '1:711849765217:web:4ed291b9872af4d0a7bd20',
    messagingSenderId: '711849765217',
    projectId: 'borlagh-2cc0d',
    authDomain: 'borlagh-2cc0d.firebaseapp.com',
    databaseURL: 'https://borlagh-2cc0d-default-rtdb.firebaseio.com',
    storageBucket: 'borlagh-2cc0d.appspot.com',
    measurementId: 'G-TZKMQG6FB3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAeVr5xFxgNaJmMYM7aIN2GshOih4DBjVw',
    appId: '1:711849765217:android:7e74ce4bb6b49cf1a7bd20',
    messagingSenderId: '711849765217',
    projectId: 'borlagh-2cc0d',
    databaseURL: 'https://borlagh-2cc0d-default-rtdb.firebaseio.com',
    storageBucket: 'borlagh-2cc0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrkDOpYAGa_bKM-OnHidGNpxDiZjJxxJE',
    appId: '1:711849765217:ios:bb5f957df2ec6555a7bd20',
    messagingSenderId: '711849765217',
    projectId: 'borlagh-2cc0d',
    databaseURL: 'https://borlagh-2cc0d-default-rtdb.firebaseio.com',
    storageBucket: 'borlagh-2cc0d.appspot.com',
    iosBundleId: 'com.malcolm.borlawms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrkDOpYAGa_bKM-OnHidGNpxDiZjJxxJE',
    appId: '1:711849765217:ios:bb5f957df2ec6555a7bd20',
    messagingSenderId: '711849765217',
    projectId: 'borlagh-2cc0d',
    databaseURL: 'https://borlagh-2cc0d-default-rtdb.firebaseio.com',
    storageBucket: 'borlagh-2cc0d.appspot.com',
    iosBundleId: 'com.malcolm.borlawms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQBpnuMeV72HPEX6GwKlQouURBlUsDgwo',
    appId: '1:711849765217:web:f8d2c3268fda998ba7bd20',
    messagingSenderId: '711849765217',
    projectId: 'borlagh-2cc0d',
    authDomain: 'borlagh-2cc0d.firebaseapp.com',
    databaseURL: 'https://borlagh-2cc0d-default-rtdb.firebaseio.com',
    storageBucket: 'borlagh-2cc0d.appspot.com',
    measurementId: 'G-ZNEV75DPTY',
  );

}